image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: v1.3.1
  digest: "sha256:8e2ea7f5f9247e28663deb15e5ff6767b11c7ea25d26bd94bafe8e3e417a382a"
resources:
  requests: { cpu: 300m, memory: 512Mi }
  limits:   { cpu: 600m, memory: 1Gi }
  
ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    enabled: true
    secretName: electricity-price-prod-tls

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: true

alerts:
  enabled: true
  env: prod
  targetNamespace: electricity-prod

  latencyP95Seconds: 0.5
  cpuCoresThreshold: 0.45
  memoryThresholdMi: 800

