image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: v1.1.0
  digest: "sha256:ce7deece5dec2cbe7508015b28839655704c7162d3cb8cb9e4751b31aa27f9b9"
resources:
  requests: { cpu: 300m, memory: 512Mi }
  limits:   { cpu: 600m, memory: 1Gi }
  
ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: prod.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls: 
    enabled: true
    secretName: electricity-price-prod-tls

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: true

alerts:
  enabled: true
  env: prod
  targetNamespace: electricity-prod

  latencyP95Seconds: 0.5
  cpuCoresThreshold: 0.45
  memoryThresholdMi: 800

