image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-a85e1e0
  digest: "sha256:730f58790ec5cc01aa6a1cde904f06ee6e21766c66d4a22d73e736b56fe4046c"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


