image:
  repository: ghcr.io/igor88gomes/electricity-price
  tag: dev-4ff9c66
  digest: "sha256:81689d73997b99259eb85435b030f7b7b3ede7bd85f1eee11c25ab30a1aded9b"

probes:
  startup:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: dev.electricity-price.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    enabled: true          
    secretName: electricity-price-dev-tls 

networkPolicy:
  enabled: true

serviceMonitor:
  enabled: false

alerts:
  enabled: false


